[package]
name = "emu65el02"
version = "0.1.0"
edition = "2021"

[dependencies]
gdbstub = "0.7.3"
image = { version = "0.25.4", default-features = false, features = ["png"] }
minifb = "0.27.0"
paste = "1.0.15"
