[package]
name = "emu65el02"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
image = { version = "0.25.8", default-features = false, features = ["png"] }
minifb = "0.28.0"
paste = "1.0.15"
